theme: jekyll-theme-slate
# Austin's Portfolio

Welcome to my portfolio! Here, you'll find an overview of my skills, education, work experience, and the projects I've worked on.

---

## 🚀 About Me
I'm an IT Systems Analyst with a strong background in technology and leadership. Passionate about problem-solving and teamwork, I strive to bridge the gap between business needs and technical solutions. Currently pursuing a Bachelor's degree in Information Technology, I continuously seek opportunities to grow and expand my expertise.

---

## 🔧 Skills & Proficiencies
- **Programming Languages:** Python, JavaScript, HTML/CSS
- **Technologies & Tools:** Git, GitHub, Microsoft Teams, AWS
- **Soft Skills:** Leadership, Empathy, Active Listening, Team Collaboration
- **Areas of Expertise:** IT Support, Systems Analysis, Troubleshooting, Relationship Management

---

## 🎓 Education
- **Southern New Hampshire University**  
  *Bachelor’s Degree in Information Technology (In Progress)*

---

## 💼 Work Experience
- **Amazon (6+ years)**  
  *IT Systems Analyst - Fulfillment Center*
  - Provided technical support for internal systems
  - Managed relationship-building initiatives for a cohesive team environment
  - Optimized system performance and troubleshooting strategies

- **Southern New Hampshire University**  
  *Online Instructor*
  - Assisted students in learning fundamental IT concepts
  - Provided mentorship and academic guidance

---

## 🛠️ Projects
### [Project 1: Portfolio Website](#)
- Developed a personal website using GitHub Pages and Markdown
- Showcases skills, education, work experience, and projects

### [Project 2: IT Support Automation Script](#)
- Automated troubleshooting steps for common IT support issues
- Written in Python to improve efficiency in the workplace

### [Project 3: Cloud Deployment Strategy](#)
- Designed and implemented a cloud migration strategy for a fulfillment center
- Utilized AWS services to optimize infrastructure

---

## 📫 Contact Me
Feel free to connect with me!
- **GitHub:** [github.com/yourusername](https://github.com/yourusername)
- **LinkedIn:** [linkedin.com/in/yourname](https://linkedin.com/in/yourname)
- **Email:** your.email@example.com

